version: "3.8"
services:
  backend:
    # build: ./backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    # build: ./frontend
    build: 
      context: ./frontend # to specify the path of the Dockerfile and the name of the Dockerfile
      dockerfile: Dockerfile
    container_name: frontend-container
    volumes:
      - ./frontend:/app
      - /app/node_modules #to make sure the node_modules will not be delete after we mounted by ./frontend:/app
      # it will be mouted to a volume which managed by docker
    ports:
      - '3000:3000'
    stdin_open: true