version: "3.8"
services:
  backend:
    # build: ./backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    # build: ./frontend
    build: 
      context: ./frontend # to specify the path of the Dockerfile and the name of the Dockerfile
      dockerfile: Dockerfile
    container_name: frontend-container
    volumes:
      - ./frontend:/app
      - /app/node_modules #to make sure the node_modules will not be delete after we mounted by ./frontend:/app
      # it will be mouted to a volume which managed by docker
    ports:
      - '3000:3000'
    stdin_open: true

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres_test #postgres
        POSTGRES_PASSWORD: postgres_tes #1234
        PGDATA: /var/lib/postgresql/data
    volumes:
        - db-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
volumes:
    db-data:
    pgadmin-data: